package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table CHAPTER_TREE.
 */
public class ChapterTree {

    private String id;
    private String chaptertree;
    private String version;

    public ChapterTree() {
    }

    public ChapterTree(String id) {
        this.id = id;
    }

    public ChapterTree(String id, String chaptertree, String version) {
        this.id = id;
        this.chaptertree = chaptertree;
        this.version = version;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getChaptertree() {
        return chaptertree;
    }

    public void setChaptertree(String chaptertree) {
        this.chaptertree = chaptertree;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

}
