package com.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.greendao.StudyRecordsDao;
import com.greendao.ExerciseDownloadPackageDao;
import com.greendao.QuestionDetailDao;
import com.greendao.ExerciseStoreDao;
import com.greendao.ExamSubjectDao;
import com.greendao.ChapterTreeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /**
     * Creates underlying database table using DAOs.
     */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        StudyRecordsDao.createTable(db, ifNotExists);
        ExerciseDownloadPackageDao.createTable(db, ifNotExists);
        QuestionDetailDao.createTable(db, ifNotExists);
        ExerciseStoreDao.createTable(db, ifNotExists);
        ExamSubjectDao.createTable(db, ifNotExists);
        ChapterTreeDao.createTable(db, ifNotExists);
    }

    /**
     * Drops underlying database table using DAOs.
     */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        StudyRecordsDao.dropTable(db, ifExists);
        ExerciseDownloadPackageDao.dropTable(db, ifExists);
        QuestionDetailDao.dropTable(db, ifExists);
        ExerciseStoreDao.dropTable(db, ifExists);
        ExamSubjectDao.dropTable(db, ifExists);
        ChapterTreeDao.dropTable(db, ifExists);
    }

    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(StudyRecordsDao.class);
        registerDaoClass(ExerciseDownloadPackageDao.class);
        registerDaoClass(QuestionDetailDao.class);
        registerDaoClass(ExerciseStoreDao.class);
        registerDaoClass(ExamSubjectDao.class);
        registerDaoClass(ChapterTreeDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

}
