package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.bluelinelabs.logansquare.annotation.JsonObject;

import java.io.Serializable;
import java.lang.Override;
import java.lang.String;
import java.util.List;

/**
 * Entity mapped to table DIRECT_BEAN.
 */
@JsonObject(fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS)
public class DirectBean implements Serializable {


    //videoType 1:直播  0:网课 | video_status 0正在播放 1未开始 2有回放 3回放地址未生成
    //0|x:bjy点播      1|x|lubourl!=null:互动展示点播   1|0|lubourl==null:bjy直播  1|2|lubourl==null:bjy回放

    private Long id;
    private String rid;
    private String TeacherDesc;
    private String Title;
    private String classTitle;
    private String lessionCount;
    private String price;
    private Double ActualPrice;
    private String scaleimg;
    private String buy_lives;
    private String is_fufei;
    private String content;
    private String is_zhibo;
    private String passwd;
    private String yuming;
    private String number;
    private String liveid;
    /**
     * 0正在播放 1未开始 2有回放 3回放地址未生成
     */
    private String video_status;
    private String riqi;
    private String is_buy;
    private String timeLength;
    private String zhibotime;
    private String zhiboendtime;
    private String kouling;
    private String zhibourl;
    private String lubourl;
    private String EffectDateDesc;
    private String photo_url;
    private String Brief;
    private String phaseName;
    private String ClassNo;
    private String is_living;
    private String TypeName;
    private Integer seq;
    private String isHasJy;
    /**
     * 1:直播  0:网课
     */
    private Integer videoType;
    private String ccUid;
    private String ccApi_key;
    private String ccCourses_id;
    private Integer isTrial;
    private String lessonid;

    private String NetClassId;
    private String netclass_pdf;
    private String is_ax_Type;
    private String localPath;
    private String userid;
    private String errorcode;
    private Long start;
    private Long end;
    private Long position;
    private String down_status;
    private Integer footprint;
    private Integer status;
    private String camera;
    private String customer;
    private String hd;
    private String oid;
    private String is_next_day;
    private String pic;
    private String Common_problem;
    private Integer course;
    private Boolean is_last;
    private String bjytoken;
    private String bjyvideoid;
    private boolean isCheck;
    private int fstatus = 0;//1可以提现；2已经提过；0不可以提现
    private double returncash = 0.0;////返现金额0或其他，返现金额大于0即可以提现
    private int progress = 0;////返现进度，达到100可以提现，否则不能提现、返现金额返回为0
    private String ftype = "0";//返现方式（0支付宝；1网站微信；2APP微信 3金币 以支付宝方式返回）没有则为空字符串
    private String returnaccount;//返现账号，只有微信有

    private String androidqqidkey;
    private Integer back_now;//1为返现课程0不是
    private String disproperty;//优惠方式，1是正常，2是特价，3是秒杀
    private String dis;//折扣数，空字符串代表没有折扣
    private String branchschoolid;//小能客服ID
    private List<String> gift;//赠品列表
    private String giveaway;//赠品，1有0无
    private Integer count_down;//倒计时时间戳
    private String state;//0表示无活动，1表示活动未开始，2表示活动正在进行中，3表示活动已结束
    private String seckillcount;//秒杀的数量
    private Integer seckill;//秒杀中剩余数量
    private String disPrice;//秒杀或特价的价格
    private String discount;//折扣数
    private String start_time;//活动开始时间
    private Integer mostrcash;//最高返现金额 为0时没有返现

    private String orderid;//购买课程下单的订单号
    private String room_id; //百家云直播房间id
    private String session_id;  //百家云回放的序列号
    private String student_code; // 百家云直播参加码
    private String bjyhftoken;  //百家云回放token


    private String isTimeout;//判断该课程是否过期

    private String CreateDate;//课程创建时间


    private String course_live_start_time;
    private String course_live_end_time;

    private String course_teaching_method;
    private String course_examination_method;
    private String course_examination;
    private String course_study_section;
    private String course_subject;
    private String course_agreement;
    private String course_class_type;
    private String course_province;
    private String course_cashback_hour;
    private String course_audition_nature;
    private boolean course_1to1;
    private boolean course_agreement_class;
    private boolean course_series_class;
    private boolean course_video_review;
    private String course_courseware_nature;
    private String course_video_review_frequency;
    private String useday;
    private String EndDate;
    private String terminal_time;


    public DirectBean() {
    }


    public String getCourse_live_start_time() {
        return course_live_start_time;
    }

    public void setCourse_live_start_time(String course_live_start_time) {
        this.course_live_start_time = course_live_start_time;
    }

    public String getCourse_live_end_time() {
        return course_live_end_time;
    }

    public void setCourse_live_end_time(String course_live_end_time) {
        this.course_live_end_time = course_live_end_time;
    }

    public String getCourse_teaching_method() {
        return course_teaching_method;
    }

    public void setCourse_teaching_method(String course_teaching_method) {
        this.course_teaching_method = course_teaching_method;
    }

    public String getCourse_examination_method() {
        return course_examination_method;
    }

    public void setCourse_examination_method(String course_examination_method) {
        this.course_examination_method = course_examination_method;
    }

    public String getCourse_examination() {
        return course_examination;
    }

    public void setCourse_examination(String course_examination) {
        this.course_examination = course_examination;
    }

    public String getCourse_study_section() {
        return course_study_section;
    }

    public void setCourse_study_section(String course_study_section) {
        this.course_study_section = course_study_section;
    }

    public String getCourse_subject() {
        return course_subject;
    }

    public void setCourse_subject(String course_subject) {
        this.course_subject = course_subject;
    }

    public String getCourse_agreement() {
        return course_agreement;
    }

    public void setCourse_agreement(String course_agreement) {
        this.course_agreement = course_agreement;
    }

    public String getCourse_class_type() {
        return course_class_type;
    }

    public void setCourse_class_type(String course_class_type) {
        this.course_class_type = course_class_type;
    }

    public String getCourse_province() {
        return course_province;
    }

    public void setCourse_province(String course_province) {
        this.course_province = course_province;
    }

    public String getCourse_cashback_hour() {
        return course_cashback_hour;
    }

    public void setCourse_cashback_hour(String course_cashback_hour) {
        this.course_cashback_hour = course_cashback_hour;
    }

    public String getCourse_audition_nature() {
        return course_audition_nature;
    }

    public void setCourse_audition_nature(String course_audition_nature) {
        this.course_audition_nature = course_audition_nature;
    }

    public boolean isCourse_1to1() {
        return course_1to1;
    }

    public void setCourse_1to1(boolean course_1to1) {
        this.course_1to1 = course_1to1;
    }

    public boolean isCourse_agreement_class() {
        return course_agreement_class;
    }

    public void setCourse_agreement_class(boolean course_agreement_class) {
        this.course_agreement_class = course_agreement_class;
    }

    public boolean isCourse_series_class() {
        return course_series_class;
    }

    public void setCourse_series_class(boolean course_series_class) {
        this.course_series_class = course_series_class;
    }

    public boolean isCourse_video_review() {
        return course_video_review;
    }

    public void setCourse_video_review(boolean course_video_review) {
        this.course_video_review = course_video_review;
    }

    public String getCourse_courseware_nature() {
        return course_courseware_nature;
    }

    public void setCourse_courseware_nature(String course_courseware_nature) {
        this.course_courseware_nature = course_courseware_nature;
    }

    public String getCourse_video_review_frequency() {
        return course_video_review_frequency;
    }

    public void setCourse_video_review_frequency(String course_video_review_frequency) {
        this.course_video_review_frequency = course_video_review_frequency;
    }

    public String getIsTimeout() {
        return isTimeout;
    }

    public void setIsTimeout(String isTimeout) {
        this.isTimeout = isTimeout;
    }

    public String getOrderid() {
        return orderid;
    }

    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public void setMostrcash(int mostrcash) {
        this.mostrcash = mostrcash;
    }

    public int getMostrcash() {
        return mostrcash;
    }


    public void setStart_time(String start_time) {
        this.start_time = start_time;
    }

    public String getStart_time() {
        return start_time;
    }


    public void setDiscount(String discount) {
        this.discount = discount;
    }

    public String getDiscount() {
        return discount;
    }

    public void setDisPrice(String disPrice) {
        this.disPrice = disPrice;
    }

    public String getDisPrice() {
        return disPrice;
    }

    public void setSeckill(int seckill) {
        this.seckill = seckill;
    }

    public int getSeckill() {
        return seckill;
    }

    public void setSeckillcount(String seckillcount) {
        this.seckillcount = seckillcount;
    }

    public String getSeckillcount() {
        return seckillcount;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getState() {
        return state;
    }

    public void setCount_down(int count_down) {
        this.count_down = count_down;
    }

    public int getCount_down() {
        return count_down;
    }

    public void setgiveaway(String giveaway) {
        this.giveaway = giveaway;
    }

    public String getgiveaway() {
        return giveaway;
    }

    public void setGift(List<String> gift) {
        this.gift = gift;
    }

    public List<String> getGift() {
        return gift;
    }

    public boolean isCheck() {
        return isCheck;
    }

    public void setIsCheck(boolean isCheck) {
        this.isCheck = isCheck;
    }

    public DirectBean(Long id) {
        this.id = id;
    }

    public DirectBean(Long id, String rid, String TeacherDesc, String Title, String classTitle, String lessionCount, String price, Double ActualPrice, String scaleimg, String buy_lives, String is_fufei, String content, String is_zhibo, String passwd, String yuming, String number, String liveid, String video_status, String riqi, String is_buy, String timeLength, String zhibotime, String zhiboendtime, String kouling, String zhibourl, String lubourl, String EffectDateDesc, String photo_url, String Brief, String phaseName, String ClassNo, String is_living, String TypeName, Integer seq, String isHasJy, Integer videoType, String ccUid, String ccApi_key, String ccCourses_id, Integer isTrial, String NetClassId, String netclass_pdf, String is_ax_Type, String localPath, String userid, String errorcode, Long start, Long end, Long position, String down_status, Integer footprint, Integer status, String camera, String customer, String hd, String oid, String is_next_day, String pic, String Common_problem, Integer course, Boolean is_last, String bjytoken, String bjyvideoid, String room_id, String session_id, String student_code, String bjyhftoken) {
        this.id = id;
        this.rid = rid;
        this.TeacherDesc = TeacherDesc;
        this.Title = Title;
        this.classTitle = classTitle;
        this.lessionCount = lessionCount;
        this.price = price;
        this.ActualPrice = ActualPrice;
        this.scaleimg = scaleimg;
        this.buy_lives = buy_lives;
        this.is_fufei = is_fufei;
        this.content = content;
        this.is_zhibo = is_zhibo;
        this.passwd = passwd;
        this.yuming = yuming;
        this.number = number;
        this.liveid = liveid;
        this.video_status = video_status;
        this.riqi = riqi;
        this.is_buy = is_buy;
        this.timeLength = timeLength;
        this.zhibotime = zhibotime;
        this.zhiboendtime = zhiboendtime;
        this.kouling = kouling;
        this.zhibourl = zhibourl;
        this.lubourl = lubourl;
        this.EffectDateDesc = EffectDateDesc;
        this.photo_url = photo_url;
        this.Brief = Brief;
        this.phaseName = phaseName;
        this.ClassNo = ClassNo;
        this.is_living = is_living;
        this.TypeName = TypeName;
        this.seq = seq;
        this.isHasJy = isHasJy;
        this.videoType = videoType;
        this.ccUid = ccUid;
        this.ccApi_key = ccApi_key;
        this.ccCourses_id = ccCourses_id;
        this.isTrial = isTrial;
        this.NetClassId = NetClassId;
        this.netclass_pdf = netclass_pdf;
        this.is_ax_Type = is_ax_Type;
        this.localPath = localPath;
        this.userid = userid;
        this.errorcode = errorcode;
        this.start = start;
        this.end = end;
        this.position = position;
        this.down_status = down_status;
        this.footprint = footprint;
        this.status = status;
        this.camera = camera;
        this.customer = customer;
        this.hd = hd;
        this.oid = oid;
        this.is_next_day = is_next_day;
        this.pic = pic;
        this.Common_problem = Common_problem;
        this.room_id = room_id;
        this.session_id = session_id;
        this.student_code = student_code;
        this.bjyhftoken = bjyhftoken;
    }

    public String getbranchschoolid() {
        return branchschoolid;
    }

    public void setbranchschoolid(String branchschoolid) {
        this.branchschoolid = branchschoolid;
    }

    public String getAndroidqqidkey() {
        return androidqqidkey;
    }

    public void setAndroidqqidkey(String androidqqidkey) {
        this.androidqqidkey = androidqqidkey;
    }

    public String getdisproperty() {
        return disproperty;
    }

    public void setdisproperty(String disproperty) {
        this.disproperty = disproperty;
    }

    public int getback_now() {
        return back_now;
    }

    public void setback_now(int back_now) {
        this.back_now = back_now;
    }

    public String getdis() {
        return dis;
    }

    public void setdis(String dis) {
        this.dis = dis;
    }

    public int getcourse() {
        return course;
    }

    public void setcourse(int course) {
        this.course = course;
        this.is_last = is_last;
        this.bjytoken = bjytoken;
        this.bjyvideoid = bjyvideoid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRid() {
        return rid;
    }

    public void setRid(String rid) {
        this.rid = rid;
    }

    public String getTeacherDesc() {
        return TeacherDesc;
    }

    public void setTeacherDesc(String TeacherDesc) {
        this.TeacherDesc = TeacherDesc;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getClassTitle() {
        return classTitle;
    }

    public void setClassTitle(String classTitle) {
        this.classTitle = classTitle;
    }

    public String getLessionCount() {
        return lessionCount;
    }

    public void setLessionCount(String lessionCount) {
        this.lessionCount = lessionCount;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Double getActualPrice() {
        return ActualPrice;
    }

    public void setActualPrice(Double ActualPrice) {
        this.ActualPrice = ActualPrice;
    }

    public String getScaleimg() {
        return scaleimg;
    }

    public void setScaleimg(String scaleimg) {
        this.scaleimg = scaleimg;
    }

    public String getBuy_lives() {
        return buy_lives;
    }

    public void setBuy_lives(String buy_lives) {
        this.buy_lives = buy_lives;
    }

    public String getIs_fufei() {
        return is_fufei;
    }

    public void setIs_fufei(String is_fufei) {
        this.is_fufei = is_fufei;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getIs_zhibo() {
        return is_zhibo;
    }

    public void setIs_zhibo(String is_zhibo) {
        this.is_zhibo = is_zhibo;
    }

    public String getPasswd() {
        return passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public String getYuming() {
        return yuming;
    }

    public void setYuming(String yuming) {
        this.yuming = yuming;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getLiveid() {
        return liveid;
    }

    public void setLiveid(String liveid) {
        this.liveid = liveid;
    }

    public String getVideo_status() {
        return video_status;
    }

    public void setVideo_status(String video_status) {
        this.video_status = video_status;
    }

    public String getRiqi() {
        return riqi;
    }

    public void setRiqi(String riqi) {
        this.riqi = riqi;
    }

    public String getIs_buy() {
        return is_buy;
    }

    public void setIs_buy(String is_buy) {
        this.is_buy = is_buy;
    }

    public String getTimeLength() {
        return timeLength;
    }

    public void setTimeLength(String timeLength) {
        this.timeLength = timeLength;
    }

    public String getZhibotime() {
        return zhibotime;
    }

    public void setZhibotime(String zhibotime) {
        this.zhibotime = zhibotime;
    }

    public String getZhiboendtime() {
        return zhiboendtime;
    }

    public void setZhiboendtime(String zhiboendtime) {
        this.zhiboendtime = zhiboendtime;
    }

    public String getKouling() {
        return kouling;
    }

    public void setKouling(String kouling) {
        this.kouling = kouling;
    }

    public String getZhibourl() {
        return zhibourl;
    }

    public void setZhibourl(String zhibourl) {
        this.zhibourl = zhibourl;
    }

    public String getLubourl() {
        return lubourl;
    }

    public void setLubourl(String lubourl) {
        this.lubourl = lubourl;
    }

    public String getEffectDateDesc() {
        return EffectDateDesc;
    }

    public void setEffectDateDesc(String EffectDateDesc) {
        this.EffectDateDesc = EffectDateDesc;
    }

    public String getPhoto_url() {
        return photo_url;
    }

    public void setPhoto_url(String photo_url) {
        this.photo_url = photo_url;
    }

    public String getBrief() {
        return Brief;
    }

    public void setBrief(String Brief) {
        this.Brief = Brief;
    }

    public String getPhaseName() {
        return phaseName;
    }

    public void setPhaseName(String phaseName) {
        this.phaseName = phaseName;
    }

    public String getClassNo() {
        return ClassNo;
    }

    public void setClassNo(String ClassNo) {
        this.ClassNo = ClassNo;
    }

    public String getIs_living() {
        return is_living;
    }

    public void setIs_living(String is_living) {
        this.is_living = is_living;
    }

    public String getTypeName() {
        return TypeName;
    }

    public void setTypeName(String TypeName) {
        this.TypeName = TypeName;
    }

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getIsHasJy() {
        return isHasJy;
    }

    public void setIsHasJy(String isHasJy) {
        this.isHasJy = isHasJy;
    }

    public Integer getVideoType() {
        return videoType;
    }

    public void setVideoType(Integer videoType) {
        this.videoType = videoType;
    }

    public String getCcUid() {
        return ccUid;
    }

    public void setCcUid(String ccUid) {
        this.ccUid = ccUid;
    }

    public String getCcApi_key() {
        return ccApi_key;
    }

    public void setCcApi_key(String ccApi_key) {
        this.ccApi_key = ccApi_key;
    }

    public String getCcCourses_id() {
        return ccCourses_id;
    }

    public void setCcCourses_id(String ccCourses_id) {
        this.ccCourses_id = ccCourses_id;
    }

    public Integer getIsTrial() {
        return isTrial;
    }

    public void setIsTrial(Integer isTrial) {
        this.isTrial = isTrial;
    }

    public String getLessonid() {
        return lessonid;
    }

    public void setLessonid(String lessionid) {
        this.lessonid = lessionid;
    }

    public String getNetClassId() {
        return NetClassId;
    }

    public void setNetClassId(String NetClassId) {
        this.NetClassId = NetClassId;
    }

    public String getNetclass_pdf() {
        return netclass_pdf;
    }

    public void setNetclass_pdf(String netclass_pdf) {
        this.netclass_pdf = netclass_pdf;
    }

    public String getIs_ax_Type() {
        return is_ax_Type;
    }

    public void setIs_ax_Type(String is_ax_Type) {
        this.is_ax_Type = is_ax_Type;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getErrorcode() {
        return errorcode;
    }

    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getPosition() {
        return position;
    }

    public void setPosition(Long position) {
        this.position = position;
    }

    public String getDown_status() {
        return down_status;
    }

    public void setDown_status(String down_status) {
        this.down_status = down_status;
    }

    public Integer getFootprint() {
        return footprint;
    }

    public void setFootprint(Integer footprint) {
        this.footprint = footprint;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getCamera() {
        return camera;
    }

    public void setCamera(String camera) {
        this.camera = camera;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getHd() {
        return hd;
    }

    public void setHd(String hd) {
        this.hd = hd;
    }

    public String getOid() {
        return oid;
    }

    public void setOid(String oid) {
        this.oid = oid;
    }

    public String getIs_next_day() {
        return is_next_day;
    }

    public void setIs_next_day(String is_next_day) {
        this.is_next_day = is_next_day;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getCommon_problem() {
        return Common_problem;
    }

    public void setCommon_problem(String Common_problem) {
        this.Common_problem = Common_problem;
    }

    public Integer getCourse() {
        return course;
    }

    public void setCourse(Integer course) {
        this.course = course;
    }

    public Boolean getIs_last() {
        return is_last;
    }

    public void setIs_last(Boolean is_last) {
        this.is_last = is_last;
    }

    public String getBjytoken() {
        return bjytoken;
    }

    public void setBjytoken(String bjytoken) {
        this.bjytoken = bjytoken;
    }

    public String getBjyvideoid() {
        return bjyvideoid;
    }

    public void setBjyvideoid(String bjyvideoid) {
        this.bjyvideoid = bjyvideoid;
    }

    public int getFstatus() {
        return fstatus;
    }

    public void setFstatus(int fstatus) {
        this.fstatus = fstatus;
    }

    public double getReturncash() {
        return returncash;
    }

    public void setReturncash(int returncash) {
        this.returncash = returncash;
    }

    public int getProgress() {
        return progress;
    }

    public void setProgress(int progress) {
        this.progress = progress;
    }

    public String getFtype() {
        return ftype;
    }

    public void setFtype(String ftype) {
        this.ftype = ftype;
    }

    public void setReturncash(double returncash) {
        this.returncash = returncash;
    }

    public String getReturnaccount() {
        return returnaccount;
    }

    public void setReturnaccount(String returnaccount) {
        this.returnaccount = returnaccount;
    }

    public String getRoom_id() {
        return room_id;
    }

    public void setRoom_id(String room_id) {
        this.room_id = room_id;
    }

    public String getSession_id() {
        return session_id;
    }

    public void setSession_id(String session_id) {
        this.session_id = session_id;
    }

    public String getStudent_code() {
        return student_code;
    }

    public void setStudent_code(String student_code) {
        this.student_code = student_code;
    }

    public String getBjyhftoken() {
        return bjyhftoken;
    }

    public void setBjyhftoken(String bjyhftoken) {
        this.bjyhftoken = bjyhftoken;
    }

    public String getCreateDate() {
        return CreateDate;
    }

    public void setCreateDate(String createDate) {
        CreateDate = createDate;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DirectBean that = (DirectBean) o;

        if (id != null ? !id.equals(that.id) : that.id != null) return false;
        if (rid != null ? !rid.equals(that.rid) : that.rid != null) return false;
        if (video_status != null ? !video_status.equals(that.video_status) : that.video_status != null)
            return false;
        if (is_buy != null ? !is_buy.equals(that.is_buy) : that.is_buy != null) return false;
        if (zhibotime != null ? !zhibotime.equals(that.zhibotime) : that.zhibotime != null)
            return false;
        if (zhiboendtime != null ? !zhiboendtime.equals(that.zhiboendtime) : that.zhiboendtime != null)
            return false;
        if (lubourl != null ? !lubourl.equals(that.lubourl) : that.lubourl != null) return false;
        if (isHasJy != null ? !isHasJy.equals(that.isHasJy) : that.isHasJy != null) return false;
        if (videoType != null ? !videoType.equals(that.videoType) : that.videoType != null)
            return false;
        if (isTrial != null ? !isTrial.equals(that.isTrial) : that.isTrial != null) return false;
        if (NetClassId != null ? !NetClassId.equals(that.NetClassId) : that.NetClassId != null)
            return false;
        if (netclass_pdf != null ? !netclass_pdf.equals(that.netclass_pdf) : that.netclass_pdf != null)
            return false;
        if (userid != null ? !userid.equals(that.userid) : that.userid != null) return false;
        if (hd != null ? !hd.equals(that.hd) : that.hd != null) return false;
        if (bjytoken != null ? !bjytoken.equals(that.bjytoken) : that.bjytoken != null)
            return false;
        if (bjyvideoid != null ? !bjyvideoid.equals(that.bjyvideoid) : that.bjyvideoid != null)
            return false;
        if (branchschoolid != null ? !branchschoolid.equals(that.branchschoolid) : that.branchschoolid != null)
            return false;
        if (room_id != null ? !room_id.equals(that.room_id) : that.room_id != null) return false;
        if (session_id != null ? !session_id.equals(that.session_id) : that.session_id != null)
            return false;
        if (student_code != null ? !student_code.equals(that.student_code) : that.student_code != null)
            return false;
        return bjyhftoken != null ? bjyhftoken.equals(that.bjyhftoken) : that.bjyhftoken == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (rid != null ? rid.hashCode() : 0);
        result = 31 * result + (video_status != null ? video_status.hashCode() : 0);
        result = 31 * result + (is_buy != null ? is_buy.hashCode() : 0);
        result = 31 * result + (zhibotime != null ? zhibotime.hashCode() : 0);
        result = 31 * result + (zhiboendtime != null ? zhiboendtime.hashCode() : 0);
        result = 31 * result + (lubourl != null ? lubourl.hashCode() : 0);
        result = 31 * result + (isHasJy != null ? isHasJy.hashCode() : 0);
        result = 31 * result + (videoType != null ? videoType.hashCode() : 0);
        result = 31 * result + (isTrial != null ? isTrial.hashCode() : 0);
        result = 31 * result + (NetClassId != null ? NetClassId.hashCode() : 0);
        result = 31 * result + (netclass_pdf != null ? netclass_pdf.hashCode() : 0);
        result = 31 * result + (userid != null ? userid.hashCode() : 0);
        result = 31 * result + (hd != null ? hd.hashCode() : 0);
        result = 31 * result + (bjytoken != null ? bjytoken.hashCode() : 0);
        result = 31 * result + (bjyvideoid != null ? bjyvideoid.hashCode() : 0);
        result = 31 * result + (isCheck ? 1 : 0);
        result = 31 * result + (branchschoolid != null ? branchschoolid.hashCode() : 0);
        result = 31 * result + (room_id != null ? room_id.hashCode() : 0);
        result = 31 * result + (session_id != null ? session_id.hashCode() : 0);
        result = 31 * result + (student_code != null ? student_code.hashCode() : 0);
        result = 31 * result + (bjyhftoken != null ? bjyhftoken.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "DirectBean{" +
                "id=" + id +
                ", rid='" + rid + '\'' +
                ", TeacherDesc='" + TeacherDesc + '\'' +
                ", Title='" + Title + '\'' +
                ", classTitle='" + classTitle + '\'' +
                ", lessionCount='" + lessionCount + '\'' +
                ", price='" + price + '\'' +
                ", ActualPrice=" + ActualPrice +
                ", scaleimg='" + scaleimg + '\'' +
                ", buy_lives='" + buy_lives + '\'' +
                ", is_fufei='" + is_fufei + '\'' +
                ", content='" + content + '\'' +
                ", is_zhibo='" + is_zhibo + '\'' +
                ", passwd='" + passwd + '\'' +
                ", yuming='" + yuming + '\'' +
                ", number='" + number + '\'' +
                ", liveid='" + liveid + '\'' +
                ", video_status='" + video_status + '\'' +
                ", riqi='" + riqi + '\'' +
                ", is_buy='" + is_buy + '\'' +
                ", timeLength='" + timeLength + '\'' +
                ", zhibotime='" + zhibotime + '\'' +
                ", zhiboendtime='" + zhiboendtime + '\'' +
                ", kouling='" + kouling + '\'' +
                ", zhibourl='" + zhibourl + '\'' +
                ", lubourl='" + lubourl + '\'' +
                ", EffectDateDesc='" + EffectDateDesc + '\'' +
                ", photo_url='" + photo_url + '\'' +
                ", Brief='" + Brief + '\'' +
                ", phaseName='" + phaseName + '\'' +
                ", ClassNo='" + ClassNo + '\'' +
                ", is_living='" + is_living + '\'' +
                ", TypeName='" + TypeName + '\'' +
                ", seq=" + seq +
                ", isHasJy='" + isHasJy + '\'' +
                ", videoType=" + videoType +
                ", ccUid='" + ccUid + '\'' +
                ", ccApi_key='" + ccApi_key + '\'' +
                ", ccCourses_id='" + ccCourses_id + '\'' +
                ", isTrial=" + isTrial +
                ", NetClassId='" + NetClassId + '\'' +
                ", netclass_pdf='" + netclass_pdf + '\'' +
                ", is_ax_Type='" + is_ax_Type + '\'' +
                ", localPath='" + localPath + '\'' +
                ", userid='" + userid + '\'' +
                ", errorcode='" + errorcode + '\'' +
                ", start=" + start +
                ", end=" + end +
                ", position=" + position +
                ", down_status='" + down_status + '\'' +
                ", footprint=" + footprint +
                ", status=" + status +
                ", camera='" + camera + '\'' +
                ", customer='" + customer + '\'' +
                ", hd='" + hd + '\'' +
                ", oid='" + oid + '\'' +
                ", is_next_day='" + is_next_day + '\'' +
                ", pic='" + pic + '\'' +
                ", Common_problem='" + Common_problem + '\'' +
                ", course=" + course +
                ", is_last=" + is_last +
                ", bjytoken='" + bjytoken + '\'' +
                ", bjyvideoid='" + bjyvideoid + '\'' +
                ", room_id='" + room_id + '\'' +
                ", session_id='" + session_id + '\'' +
                ", student_code='" + student_code + '\'' +
                ", bjyhftoken='" + bjyhftoken + '\'' +
                ", isCheck=" + isCheck +
                ", fstatus=" + fstatus +
                ", returncash=" + returncash +
                ", progress=" + progress +
                ", ftype='" + ftype + '\'' +
//                ", back_now=" + back_now +
//                ", disproperty=" + disproperty +
                ", dis=" + dis +
                '}';
    }

    public String getUseday() {
        return useday;
    }

    public void setUseday(String useday) {
        this.useday = useday;
    }

    public String getEndDate() {
        return EndDate;
    }

    public void setEndDate(String endDate) {
        EndDate = endDate;
    }

    public String getTerminal_time() {
        return terminal_time;
    }

    public void setTerminal_time(String terminal_time) {
        this.terminal_time = terminal_time;
    }
}
