package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;

import java.io.Serializable;
import java.lang.Override;
import java.lang.String;
import java.util.Arrays;

/**
 * Entity mapped to table QUESTION_DETAIL.
 */
@JsonObject(fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS)
public class QuestionDetail implements Serializable{

    private String choices;
    private String answers;
    @JsonField
    private String author;
    @JsonField
    private String comment;
    @JsonField
    private String question;
    private String qpoint;
    @JsonField
    private String qrootpoint;
    @JsonField
    private String content;
    private String id;
    @JsonField
    private String qid;

    @JsonField(name = "answers")
    public String[] answersArr;

    @JsonField(name = "choices")
    public String[] choicesArr;

    @JsonField(name = "qrootpoint")
    public String[] qrootpointArr;

    @JsonField(name = "qpoint")
    public String[] qpointArr;

    @JsonField
    private String score;

    @JsonField
    private String qvideo;

    @JsonField
    private String qtype;

    @JsonField
    private String extension;

    private String stateQuestion; //试题状态 0正常 -1删除 1更新 包含-1E 表示错题中心不显示 -1C表示收藏中心不显示-1M表示模块题海不显示

    private int expendType = 0;//真题主观题 展开状态 0 默认不展开 1 展开

    public QuestionDetail() {
    }

    public QuestionDetail(String choices, String answers, String author, String comment, String question, String qpoint, String qrootpoint, String content, String score, String qvideo, String qtype, String extension, String stateQuestion, String id, String qid) {
        this.choices = choices;
        this.answers = answers;
        this.author = author;
        this.comment = comment;
        this.question = question;
        this.qpoint = qpoint;
        this.qrootpoint = qrootpoint;
        this.content = content;
        this.score = score;
        this.qvideo = qvideo;
        this.qtype = qtype;
        this.extension = extension;
        this.stateQuestion = stateQuestion;
        this.id = id;
        this.qid = qid;
    }

    public String getChoices() {
        return choices;
    }

    public void setChoices(String choices) {
        this.choices = choices;
    }

    public String getAnswers() {
        return answers;
    }

    public void setAnswers(String answers) {
        this.answers = answers;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    public String getQpoint() {
        return qpoint;
    }

    public void setQpoint(String qpoint) {
        this.qpoint = qpoint;
    }

    public String getQrootpoint() {
        return qrootpoint;
    }

    public void setQrootpoint(String qrootpoint) {
        this.qrootpoint = qrootpoint;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public String getQvideo() {
        return qvideo;
    }

    public void setQvideo(String qvideo) {
        this.qvideo = qvideo;
    }

    public String getQtype() {
        return qtype;
    }

    public void setQtype(String qtype) {
        this.qtype = qtype;
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getQid() {
        return qid;
    }

    public void setQid(String qid) {
        this.qid = qid;
    }

    public String getStateQuestion() {
        return stateQuestion;
    }

    public void setStateQuestion(String stateQuestion) {
        this.stateQuestion = stateQuestion;
    }

    public int getExpendType() {
        return expendType;
    }

    public void setExpendType(int expendType) {
        this.expendType = expendType;
    }

    @Override
    public String toString() {
        return "QuestionDetail{" +
                "choices='" + choices + '\'' +
                ", answers='" + answers + '\'' +
                ", author='" + author + '\'' +
                ", comment='" + comment + '\'' +
                ", question='" + question + '\'' +
                ", qpoint='" + qpoint + '\'' +
                ", qrootpoint='" + qrootpoint + '\'' +
                ", content='" + content + '\'' +
                ", id='" + id + '\'' +
                ", qid='" + qid + '\'' +
                ", answersArr=" + Arrays.toString(answersArr) +
                ", choicesArr=" + Arrays.toString(choicesArr) +
                ", qrootpointArr=" + Arrays.toString(qrootpointArr) +
                ", qpointArr=" + Arrays.toString(qpointArr) +
                ", score='" + score + '\'' +
                ", qvideo='" + qvideo + '\'' +
                ", qtype='" + qtype + '\'' +
                ", extension='" + extension + '\'' +
                ", stateQuestion='" + stateQuestion + '\'' +
                ", expendType=" + expendType +
                '}';
    }
}
