package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;
import java.lang.Override;
import java.lang.String;

/**
 * Entity mapped to table DIRECT_BEAN.
 */
@JsonObject(fieldDetectionPolicy = JsonObject.FieldDetectionPolicy.NONPRIVATE_FIELDS_AND_ACCESSORS)
public class DirectBean implements Serializable{

    private Long id;
    private String rid;
    private String TeacherDesc;
    private String Title;
    private String classTitle;
    private String lessionCount;
    private String price;
    private Double ActualPrice;
    private String scaleimg;
    private String buy_lives;
    private String is_fufei;
    private String content;
    private String is_zhibo;
    private String passwd;
    private String yuming;
    private String number;
    private String liveid;
    private String video_status;
    private String riqi;
    private String is_buy;
    private String timeLength;
    private String zhibotime;
    private String zhiboendtime;
    private String kouling;
    private String zhibourl;
    private String lubourl;
    private String EffectDateDesc;
    private String photo_url;
    private String Brief;
    private String phaseName;
    private String ClassNo;
    private String is_living;
    private String TypeName;
    private Integer seq;
    private String isHasJy;
    private Integer videoType;
    private String ccUid;
    private String ccApi_key;
    private String ccCourses_id;
    private Integer isTrial;
    private String NetClassId;
    private String netclass_pdf;
    private String is_ax_Type;
    private String localPath;
    private String userid;
    private String errorcode;
    private Long start;
    private Long end;
    private Long position;
    private String down_status;
    private Integer footprint;
    private Integer status;
    private String camera;
    private String customer;
    private String hd;
    private String oid;
    private String is_next_day;
    private String pic;
    private String Common_problem;
    private Integer course;
    private Boolean is_last;
    private String bjytoken;
    private String bjyvideoid;
    private boolean isCheck;

    public DirectBean() {
    }

    public boolean isCheck() {
        return isCheck;
    }

    public void setIsCheck(boolean isCheck) {
        this.isCheck = isCheck;
    }

    public DirectBean(Long id) {
        this.id = id;
    }

    public DirectBean(Long id, String rid, String TeacherDesc, String Title, String classTitle, String lessionCount, String price, Double ActualPrice, String scaleimg, String buy_lives, String is_fufei, String content, String is_zhibo, String passwd, String yuming, String number, String liveid, String video_status, String riqi, String is_buy, String timeLength, String zhibotime, String zhiboendtime, String kouling, String zhibourl, String lubourl, String EffectDateDesc, String photo_url, String Brief, String phaseName, String ClassNo, String is_living, String TypeName, Integer seq, String isHasJy, Integer videoType, String ccUid, String ccApi_key, String ccCourses_id, Integer isTrial, String NetClassId, String netclass_pdf, String is_ax_Type, String localPath, String userid, String errorcode, Long start, Long end, Long position, String down_status, Integer footprint, Integer status, String camera, String customer, String hd, String oid, String is_next_day, String pic, String Common_problem, Integer course, Boolean is_last, String bjytoken, String bjyvideoid) {
        this.id = id;
        this.rid = rid;
        this.TeacherDesc = TeacherDesc;
        this.Title = Title;
        this.classTitle = classTitle;
        this.lessionCount = lessionCount;
        this.price = price;
        this.ActualPrice = ActualPrice;
        this.scaleimg = scaleimg;
        this.buy_lives = buy_lives;
        this.is_fufei = is_fufei;
        this.content = content;
        this.is_zhibo = is_zhibo;
        this.passwd = passwd;
        this.yuming = yuming;
        this.number = number;
        this.liveid = liveid;
        this.video_status = video_status;
        this.riqi = riqi;
        this.is_buy = is_buy;
        this.timeLength = timeLength;
        this.zhibotime = zhibotime;
        this.zhiboendtime = zhiboendtime;
        this.kouling = kouling;
        this.zhibourl = zhibourl;
        this.lubourl = lubourl;
        this.EffectDateDesc = EffectDateDesc;
        this.photo_url = photo_url;
        this.Brief = Brief;
        this.phaseName = phaseName;
        this.ClassNo = ClassNo;
        this.is_living = is_living;
        this.TypeName = TypeName;
        this.seq = seq;
        this.isHasJy = isHasJy;
        this.videoType = videoType;
        this.ccUid = ccUid;
        this.ccApi_key = ccApi_key;
        this.ccCourses_id = ccCourses_id;
        this.isTrial = isTrial;
        this.NetClassId = NetClassId;
        this.netclass_pdf = netclass_pdf;
        this.is_ax_Type = is_ax_Type;
        this.localPath = localPath;
        this.userid = userid;
        this.errorcode = errorcode;
        this.start = start;
        this.end = end;
        this.position = position;
        this.down_status = down_status;
        this.footprint = footprint;
        this.status = status;
        this.camera = camera;
        this.customer = customer;
        this.hd = hd;
        this.oid = oid;
        this.is_next_day = is_next_day;
        this.pic = pic;
        this.Common_problem = Common_problem;
        this.course = course;
        this.is_last = is_last;
        this.bjytoken = bjytoken;
        this.bjyvideoid = bjyvideoid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRid() {
        return rid;
    }

    public void setRid(String rid) {
        this.rid = rid;
    }

    public String getTeacherDesc() {
        return TeacherDesc;
    }

    public void setTeacherDesc(String TeacherDesc) {
        this.TeacherDesc = TeacherDesc;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getClassTitle() {
        return classTitle;
    }

    public void setClassTitle(String classTitle) {
        this.classTitle = classTitle;
    }

    public String getLessionCount() {
        return lessionCount;
    }

    public void setLessionCount(String lessionCount) {
        this.lessionCount = lessionCount;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Double getActualPrice() {
        return ActualPrice;
    }

    public void setActualPrice(Double ActualPrice) {
        this.ActualPrice = ActualPrice;
    }

    public String getScaleimg() {
        return scaleimg;
    }

    public void setScaleimg(String scaleimg) {
        this.scaleimg = scaleimg;
    }

    public String getBuy_lives() {
        return buy_lives;
    }

    public void setBuy_lives(String buy_lives) {
        this.buy_lives = buy_lives;
    }

    public String getIs_fufei() {
        return is_fufei;
    }

    public void setIs_fufei(String is_fufei) {
        this.is_fufei = is_fufei;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getIs_zhibo() {
        return is_zhibo;
    }

    public void setIs_zhibo(String is_zhibo) {
        this.is_zhibo = is_zhibo;
    }

    public String getPasswd() {
        return passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public String getYuming() {
        return yuming;
    }

    public void setYuming(String yuming) {
        this.yuming = yuming;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getLiveid() {
        return liveid;
    }

    public void setLiveid(String liveid) {
        this.liveid = liveid;
    }

    public String getVideo_status() {
        return video_status;
    }

    public void setVideo_status(String video_status) {
        this.video_status = video_status;
    }

    public String getRiqi() {
        return riqi;
    }

    public void setRiqi(String riqi) {
        this.riqi = riqi;
    }

    public String getIs_buy() {
        return is_buy;
    }

    public void setIs_buy(String is_buy) {
        this.is_buy = is_buy;
    }

    public String getTimeLength() {
        return timeLength;
    }

    public void setTimeLength(String timeLength) {
        this.timeLength = timeLength;
    }

    public String getZhibotime() {
        return zhibotime;
    }

    public void setZhibotime(String zhibotime) {
        this.zhibotime = zhibotime;
    }

    public String getZhiboendtime() {
        return zhiboendtime;
    }

    public void setZhiboendtime(String zhiboendtime) {
        this.zhiboendtime = zhiboendtime;
    }

    public String getKouling() {
        return kouling;
    }

    public void setKouling(String kouling) {
        this.kouling = kouling;
    }

    public String getZhibourl() {
        return zhibourl;
    }

    public void setZhibourl(String zhibourl) {
        this.zhibourl = zhibourl;
    }

    public String getLubourl() {
        return lubourl;
    }

    public void setLubourl(String lubourl) {
        this.lubourl = lubourl;
    }

    public String getEffectDateDesc() {
        return EffectDateDesc;
    }

    public void setEffectDateDesc(String EffectDateDesc) {
        this.EffectDateDesc = EffectDateDesc;
    }

    public String getPhoto_url() {
        return photo_url;
    }

    public void setPhoto_url(String photo_url) {
        this.photo_url = photo_url;
    }

    public String getBrief() {
        return Brief;
    }

    public void setBrief(String Brief) {
        this.Brief = Brief;
    }

    public String getPhaseName() {
        return phaseName;
    }

    public void setPhaseName(String phaseName) {
        this.phaseName = phaseName;
    }

    public String getClassNo() {
        return ClassNo;
    }

    public void setClassNo(String ClassNo) {
        this.ClassNo = ClassNo;
    }

    public String getIs_living() {
        return is_living;
    }

    public void setIs_living(String is_living) {
        this.is_living = is_living;
    }

    public String getTypeName() {
        return TypeName;
    }

    public void setTypeName(String TypeName) {
        this.TypeName = TypeName;
    }

    public Integer getSeq() {
        return seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getIsHasJy() {
        return isHasJy;
    }

    public void setIsHasJy(String isHasJy) {
        this.isHasJy = isHasJy;
    }

    public Integer getVideoType() {
        return videoType;
    }

    public void setVideoType(Integer videoType) {
        this.videoType = videoType;
    }

    public String getCcUid() {
        return ccUid;
    }

    public void setCcUid(String ccUid) {
        this.ccUid = ccUid;
    }

    public String getCcApi_key() {
        return ccApi_key;
    }

    public void setCcApi_key(String ccApi_key) {
        this.ccApi_key = ccApi_key;
    }

    public String getCcCourses_id() {
        return ccCourses_id;
    }

    public void setCcCourses_id(String ccCourses_id) {
        this.ccCourses_id = ccCourses_id;
    }

    public Integer getIsTrial() {
        return isTrial;
    }

    public void setIsTrial(Integer isTrial) {
        this.isTrial = isTrial;
    }

    public String getNetClassId() {
        return NetClassId;
    }

    public void setNetClassId(String NetClassId) {
        this.NetClassId = NetClassId;
    }

    public String getNetclass_pdf() {
        return netclass_pdf;
    }

    public void setNetclass_pdf(String netclass_pdf) {
        this.netclass_pdf = netclass_pdf;
    }

    public String getIs_ax_Type() {
        return is_ax_Type;
    }

    public void setIs_ax_Type(String is_ax_Type) {
        this.is_ax_Type = is_ax_Type;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getErrorcode() {
        return errorcode;
    }

    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getPosition() {
        return position;
    }

    public void setPosition(Long position) {
        this.position = position;
    }

    public String getDown_status() {
        return down_status;
    }

    public void setDown_status(String down_status) {
        this.down_status = down_status;
    }

    public Integer getFootprint() {
        return footprint;
    }

    public void setFootprint(Integer footprint) {
        this.footprint = footprint;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getCamera() {
        return camera;
    }

    public void setCamera(String camera) {
        this.camera = camera;
    }

    public String getCustomer() {
        return customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getHd() {
        return hd;
    }

    public void setHd(String hd) {
        this.hd = hd;
    }

    public String getOid() {
        return oid;
    }

    public void setOid(String oid) {
        this.oid = oid;
    }

    public String getIs_next_day() {
        return is_next_day;
    }

    public void setIs_next_day(String is_next_day) {
        this.is_next_day = is_next_day;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public String getCommon_problem() {
        return Common_problem;
    }

    public void setCommon_problem(String Common_problem) {
        this.Common_problem = Common_problem;
    }

    public Integer getCourse() {
        return course;
    }

    public void setCourse(Integer course) {
        this.course = course;
    }

    public Boolean getIs_last() {
        return is_last;
    }

    public void setIs_last(Boolean is_last) {
        this.is_last = is_last;
    }

    public String getBjytoken() {
        return bjytoken;
    }

    public void setBjytoken(String bjytoken) {
        this.bjytoken = bjytoken;
    }

    public String getBjyvideoid() {
        return bjyvideoid;
    }

    public void setBjyvideoid(String bjyvideoid) {
        this.bjyvideoid = bjyvideoid;
    }

    @Override
    public String toString() {
        return "DirectBean{" +
                "id=" + id +
                ", rid=" + rid +
                ", TeacherDesc=" + TeacherDesc +
                ", Title=" + Title +
                ", classTitle=" + classTitle +
                ", lessionCount=" + lessionCount +
                ", price=" + price +
                ", ActualPrice=" + ActualPrice +
                ", scaleimg=" + scaleimg +
                ", buy_lives=" + buy_lives +
                ", is_fufei=" + is_fufei +
                ", content=" + content +
                ", is_zhibo=" + is_zhibo +
                ", passwd=" + passwd +
                ", yuming=" + yuming +
                ", number=" + number +
                ", liveid=" + liveid +
                ", video_status=" + video_status +
                ", riqi=" + riqi +
                ", is_buy=" + is_buy +
                ", timeLength=" + timeLength +
                ", zhibotime=" + zhibotime +
                ", zhiboendtime=" + zhiboendtime +
                ", kouling=" + kouling +
                ", zhibourl=" + zhibourl +
                ", lubourl=" + lubourl +
                ", EffectDateDesc=" + EffectDateDesc +
                ", photo_url=" + photo_url +
                ", Brief=" + Brief +
                ", phaseName=" + phaseName +
                ", ClassNo=" + ClassNo +
                ", is_living=" + is_living +
                ", TypeName=" + TypeName +
                ", seq=" + seq +
                ", isHasJy=" + isHasJy +
                ", videoType=" + videoType +
                ", ccUid=" + ccUid +
                ", ccApi_key=" + ccApi_key +
                ", ccCourses_id=" + ccCourses_id +
                ", isTrial=" + isTrial +
                ", NetClassId=" + NetClassId +
                ", netclass_pdf=" + netclass_pdf +
                ", is_ax_Type=" + is_ax_Type +
                ", localPath=" + localPath +
                ", userid=" + userid +
                ", errorcode=" + errorcode +
                ", start=" + start +
                ", end=" + end +
                ", position=" + position +
                ", down_status=" + down_status +
                ", footprint=" + footprint +
                ", status=" + status +
                ", camera=" + camera +
                ", customer=" + customer +
                ", hd=" + hd +
                ", oid=" + oid +
                ", is_next_day=" + is_next_day +
                ", pic=" + pic +
                ", Common_problem=" + Common_problem +
                ", course=" + course +
                ", is_last=" + is_last +
                ", bjytoken=" + bjytoken +
                ", bjyvideoid=" + bjyvideoid +
                ", isCheck=" + isCheck +
                '}';
    }
}
