package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EXAM_SUBJECT.
 */
public class ExamSubject {

    private String id;
    private String jsonforsubject;
    private String version;

    public ExamSubject() {
    }

    public ExamSubject(String id) {
        this.id = id;
    }

    public ExamSubject(String id, String jsonforsubject, String version) {
        this.id = id;
        this.jsonforsubject = jsonforsubject;
        this.version = version;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getJsonforsubject() {
        return jsonforsubject;
    }

    public void setJsonforsubject(String jsonforsubject) {
        this.jsonforsubject = jsonforsubject;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

}
