package com.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDY_RECORDS.
 */
public class StudyRecords {

    private Long id;
    private String cid;
    private String name;
    private String eids;
    private java.util.Date date;
    private String currentprogress;
    private String completed;
    private String choicesforuser;
    private String userid;
    /** Not-null value. */
    private String type;
    private String today;
    private Integer exercisenum;
    private String isdelete;
    private Integer usedtime;
    private Integer rightnum;
    private Integer lastprogress;
    private String ptimelimit;
    private String choosecategory;

    public StudyRecords() {
    }

    public StudyRecords(Long id) {
        this.id = id;
    }

    public StudyRecords(Long id, String cid, String name, String eids, java.util.Date date, String currentprogress, String completed, String choicesforuser, String userid, String type, String today, Integer exercisenum, String isdelete, Integer usedtime, Integer rightnum, Integer lastprogress, String ptimelimit, String choosecategory) {
        this.id = id;
        this.cid = cid;
        this.name = name;
        this.eids = eids;
        this.date = date;
        this.currentprogress = currentprogress;
        this.completed = completed;
        this.choicesforuser = choicesforuser;
        this.userid = userid;
        this.type = type;
        this.today = today;
        this.exercisenum = exercisenum;
        this.isdelete = isdelete;
        this.usedtime = usedtime;
        this.rightnum = rightnum;
        this.lastprogress = lastprogress;
        this.ptimelimit = ptimelimit;
        this.choosecategory = choosecategory;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEids() {
        return eids;
    }

    public void setEids(String eids) {
        this.eids = eids;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getCurrentprogress() {
        return currentprogress;
    }

    public void setCurrentprogress(String currentprogress) {
        this.currentprogress = currentprogress;
    }

    public String getCompleted() {
        return completed;
    }

    public void setCompleted(String completed) {
        this.completed = completed;
    }

    public String getChoicesforuser() {
        return choicesforuser;
    }

    public void setChoicesforuser(String choicesforuser) {
        this.choicesforuser = choicesforuser;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public String getToday() {
        return today;
    }

    public void setToday(String today) {
        this.today = today;
    }

    public Integer getExercisenum() {
        return exercisenum;
    }

    public void setExercisenum(Integer exercisenum) {
        this.exercisenum = exercisenum;
    }

    public String getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete;
    }

    public Integer getUsedtime() {
        return usedtime;
    }

    public void setUsedtime(Integer usedtime) {
        this.usedtime = usedtime;
    }

    public Integer getRightnum() {
        return rightnum;
    }

    public void setRightnum(Integer rightnum) {
        this.rightnum = rightnum;
    }

    public Integer getLastprogress() {
        return lastprogress;
    }

    public void setLastprogress(Integer lastprogress) {
        this.lastprogress = lastprogress;
    }

    public String getPtimelimit() {
        return ptimelimit;
    }

    public void setPtimelimit(String ptimelimit) {
        this.ptimelimit = ptimelimit;
    }

    public String getChoosecategory() {
        return choosecategory;
    }

    public void setChoosecategory(String choosecategory) {
        this.choosecategory = choosecategory;
    }

}
